# StackAPI

#### Import the necessary libraries here:

In [27]:
# your code here
import pandas as pd
import numpy as np
from stackapi import StackAPI
import json

SITE = StackAPI('stackoverflow')

comments = SITE.fetch('comments')
comments['items']
comments_df = pd.DataFrame(comments)

In [28]:
comments_df

,backoff,has_more,page,quota_max,quota_remaining,total,items
0,0,True,5,300,300,0,"{'owner': {'reputation': 639, 'user_id': 75195..."
1,0,True,5,300,300,0,"{'owner': {'reputation': 1, 'user_id': 1153281..."
2,0,True,5,300,300,0,"{'owner': {'reputation': 12615, 'user_id': 792..."
3,0,True,5,300,300,0,"{'owner': {'reputation': 372, 'user_id': 67176..."
4,0,True,5,300,300,0,"{'owner': {'reputation': 899, 'user_id': 78852..."
...,...,...,...,...,...,...,...
495,0,True,5,300,300,0,"{'owner': {'reputation': 170524, 'user_id': 10..."
496,0,True,5,300,300,0,"{'owner': {'reputation': 27046, 'user_id': 468..."
497,0,True,5,300,300,0,"{'owner': {'reputation': 149, 'user_id': 47089..."
498,0,True,5,300,300,0,"{'owner': {'reputation': 1, 'user_id': 2944613..."
499,0,True,5,300,300,0,"{'owner': {'reputation': 5525, 'user_id': 4074..."

In [14]:
#comments_df = comments_df[['creation_date','post_id','comment_id','owner','score','reply_to_user']]

In [19]:
#comments_df['owner_user_id']= comments_df['owner'].apply(lambda x: x['user_id'])

In [20]:
#comments_df

,owner,edited,score,creation_date,post_id,comment_id,reply_to_user,owner_user_id
0,"{'reputation': 809, 'user_id': 1137406, 'user_...",False,0,1573128563,58709835,103785355,NaN,1137406
1,"{'reputation': 1724, 'user_id': 7926183, 'user...",False,0,1573128562,58742800,103785354,NaN,7926183
2,"{'reputation': 1, 'user_id': 12263263, 'user_t...",False,0,1573128561,58544342,103785353,NaN,12263263
3,"{'reputation': 51, 'user_id': 7174456, 'user_t...",False,0,1573128560,58708751,103785352,NaN,7174456
4,"{'reputation': 1446, 'user_id': 1503846, 'user...",False,0,1573128560,34309723,103785351,NaN,1503846
...,...,...,...,...,...,...,...,...
495,"{'reputation': 413536, 'user_id': 1048572, 'us...",False,0,1573127674,58741100,103784823,NaN,1048572
496,"{'reputation': 972, 'user_id': 4870078, 'user_...",False,0,1573127669,58748094,103784821,NaN,4870078
497,"{'reputation': 185, 'user_id': 9988108, 'user_...",False,0,1573127667,58747507,103784820,"{'reputation': 6478, 'user_id': 5892059, 'user...",9988108
498,"{'reputation': 443, 'user_id': 2028853, 'user_...",False,0,1573127667,2998822,103784819,NaN,2028853
499,"{'reputation': 14, 'user_id': 5668586, 'user_t...",False,0,1573127667,58747550,103784818,NaN,5668586

#### Question 1: Find the questions and answers of last month.

Looking with the timestamp of today and the last month with the argument 'is_answered' true

In [17]:
# your code here
SITE = StackAPI('stackoverflow')
questions = SITE.fetch('questions', fromdate=1570532113, todate=1573214113,is_answered =False)
questions_df = pd.DataFrame(questions['items'])
questions_df

,tags,owner,is_answered,view_count,answer_count,score,last_activity_date,creation_date,question_id,link,title,last_edit_date,accepted_answer_id,bounty_amount,bounty_closes_date,closed_date,closed_reason,migrated_to,locked_date
0,"[msbuild, nuget, project]","{'reputation': 1939, 'user_id': 57737, 'user_t...",True,28,1,0,1573220730,1573136399,58750715,https://stackoverflow.com/questions/58750715/u...,Using project reference instead of nuget packa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[javascript, function, functional-programming]","{'reputation': 662, 'user_id': 3106343, 'user_...",True,3177,5,27,1573220716,1573114850,58744557,https://stackoverflow.com/questions/58744557/i...,Is this a pure function?,1.573221e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[mysql, join, subquery]","{'reputation': 367, 'user_id': 8252915, 'user_...",False,15,1,0,1573220714,1573212704,58765749,https://stackoverflow.com/questions/58765749/t...,Trouble selecting the correct information from...,1.573220e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[python, pygame, operating-system, pyglet, win...","{'reputation': 1, 'user_id': 12342061, 'user_t...",False,19,0,0,1573220702,1573200984,58762815,https://stackoverflow.com/questions/58762815/h...,How to play an mp3 file while a text based pro...,1.573221e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[pyqt, pyqtgraph]","{'reputation': 1, 'user_id': 11727735, 'user_t...",False,10,0,0,1573220688,1573211363,58765407,https://stackoverflow.com/questions/58765407/u...,Update pyqtgraph ImageView image without chang...,1.573221e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,"[php, reactphp]","{'reputation': 1, 'user_id': 12269581, 'user_t...",False,13,1,0,1573215116,1573188974,58760599,https://stackoverflow.com/questions/58760599/u...,Uncaught Error: Class &#39;React\React\EventLo...,1.573215e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,"[xcode, ios13, xcode11.1]","{'reputation': 11, 'user_id': 9527925, 'user_t...",False,220,1,0,1573215110,1573104988,58742549,https://stackoverflow.com/questions/58742549/i...,IOS 13.2 (17B84) Device Support files for Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,[google-apps-script],"{'reputation': 93, 'user_id': 7360514, 'user_t...",False,20,1,0,1573215109,1573159529,58756663,https://stackoverflow.com/questions/58756663/h...,How to replace a Video in Google Slides with a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,"[postgresql, docker]","{'reputation': 419, 'user_id': 11094437, 'user...",False,18,0,0,1573215091,1573141816,58752396,https://stackoverflow.com/questions/58752396/n...,No existing local cluster is suitable error us...,1.573215e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,"[javascript, arrays, algorithm, recursion, dra...","{'reputation': 96, 'user_id': 2757222, 'user_t...",True,70,4,1,1573215064,1573153179,58755348,https://stackoverflow.com/questions/58755348/i...,Infinite recursive box in 2d array javascript,1.573154e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Question 2: Find the most voted question today with at least a score of 5 and tagged with 'python'.

In [15]:
# your code here
questions = SITE.fetch('questions', todate=1573214113,tagged = 'python')
questions_df = pd.DataFrame(questions['items'])
questions_df.loc[questions_df['score']>=5]

,tags,owner,is_answered,view_count,answer_count,score,last_activity_date,creation_date,last_edit_date,question_id,link,title,accepted_answer_id,protected_date,closed_date,closed_reason,bounty_amount,bounty_closes_date
0,"[python, transactions, sqlite, autocommit]","{'reputation': 278, 'user_id': 561661, 'user_t...",True,9064,5,7,1573219169,1295094968,1.328620e+09,4699605,https://stackoverflow.com/questions/4699605/sq...,sqlite3 saving changes without commit command ...,NaN,NaN,NaN,NaN,NaN,NaN
2,"[python, anaconda]","{'reputation': 1777, 'user_id': 537259, 'user_...",True,536577,15,233,1573219062,1395532314,1.510066e+09,22585235,https://stackoverflow.com/questions/22585235/p...,Python Anaconda - How to Safely Uninstall,NaN,NaN,NaN,NaN,NaN,NaN
6,"[python, multiprocessing]","{'reputation': 28577, 'user_id': 76701, 'user_...",False,37,1,6,1573218959,1573136852,NaN,58750861,https://stackoverflow.com/questions/58750861/p...,Python multiprocessing: Running a process afte...,NaN,NaN,NaN,NaN,NaN,NaN
11,"[javascript, python, flask]","{'reputation': 470, 'user_id': 1596679, 'user_...",True,9913,1,5,1573218535,1379116750,NaN,18796921,https://stackoverflow.com/questions/18796921/p...,Passing Javascript Array to Flask,18799325.0,NaN,NaN,NaN,NaN,NaN
22,"[python, pandas, conditional]","{'reputation': 312, 'user_id': 8610662, 'user_...",True,73507,5,27,1573217853,1520456462,1.520461e+09,49161120,https://stackoverflow.com/questions/49161120/p...,Pandas/Python: Set value of one column based o...,49161313.0,NaN,NaN,NaN,NaN,NaN
25,"[python, list]","{'reputation': 23754, 'user_id': 206504, 'user...",True,3146325,7,1835,1573217752,1257899454,1.560419e+09,1712227,https://stackoverflow.com/questions/1712227/ho...,How do I get the number of elements in a list?,1712236.0,1.379709e+09,NaN,NaN,NaN,NaN
27,"[python, python-2.7, dictionary, key]","{'reputation': 77, 'user_id': 3510615, 'user_t...",True,6550,3,9,1573217743,1410342692,NaN,25762332,https://stackoverflow.com/questions/25762332/h...,How to get all the keys with the same highest ...,25762496.0,NaN,NaN,NaN,NaN,NaN
34,"[python, testing, pytest]","{'reputation': 4359, 'user_id': 3284878, 'user...",True,42365,3,163,1573217183,1451074100,1.544436e+09,34466027,https://stackoverflow.com/questions/34466027/i...,"In pytest, what is the use of conftest.py files?",34520971.0,NaN,NaN,NaN,NaN,NaN
39,"[python, python-3.x, machine-learning, scikit-...","{'reputation': 978, 'user_id': 1438637, 'user_...",True,3288,3,18,1573216893,1344641082,1.344641e+09,11910481,https://stackoverflow.com/questions/11910481/b...,Best Machine Learning package for Python 3x?,11912783.0,NaN,NaN,NaN,NaN,NaN
41,"[python, pandas]","{'reputation': 2057, 'user_id': 5013143, 'user...",True,55933,3,21,1573216770,1461601588,NaN,36846060,https://stackoverflow.com/questions/36846060/h...,how to replace an entire column on Pandas.Data...,36846100.0,NaN,NaN,NaN,NaN,NaN
52,"[python, pandas, chained-assignment]","{'reputation': 927, 'user_id': 120191, 'user_t...",True,3776,3,17,1573216154,1470529120,1.512148e+09,38809796,https://stackoverflow.com/questions/38809796/p...,Pandas still getting SettingWithCopyWarning ev...,38810015.0,NaN,NaN,NaN,NaN,NaN
61,"[python, http, sniffer]","{'reputation': 172, 'user_id': 2196301, 'user_...",True,26614,4,16,1573215821,1365521865,1.365522e+09,15906308,https://stackoverflow.com/questions/15906308/h...,How to sniff HTTP packets in python?,NaN,NaN,NaN,NaN,NaN,NaN
83,"[python, proxy, pip]","{'reputation': 4818, 'user_id': 676001, 'user_...",True,658500,31,270,1573214837,1357258937,1.560849e+09,14149422,https://stackoverflow.com/questions/14149422/u...,Using pip behind a proxy with CNTLM,14188155.0,NaN,NaN,NaN,NaN,NaN
136,[python],"{'reputation': 44, 'user_id': 4348995, 'user_t...",True,13950,3,6,1573212132,1418287188,1.418291e+09,27418527,https://stackoverflow.com/questions/27418527/p...,PostgreSQL + Python: Close connection,NaN,NaN,NaN,NaN,NaN,NaN
147,"[python, django, python-2.7, django-models]","{'reputation': 541, 'user_id': 3553893, 'user_...",True,31841,8,15,1573211796,1444220205,NaN,32991965,https://stackoverflow.com/questions/32991965/y...,You are trying to add a non-nullable field &#3...,32992737.0,NaN,NaN,NaN,NaN,NaN
148,"[python, jwt]","{'reputation': 518, 'user_id': 4375835, 'user_...",True,19410,5,40,1573211754,1445174742,1.573212e+09,33198428,https://stackoverflow.com/questions/33198428/j...,JWT: &#39;module&#39; object has no attribute ...,NaN,1.551981e+09,NaN,NaN,NaN,NaN
150,"[python, directory, os.path]","{'reputation': 469, 'user_id': 1834048, 'user_...",True,107075,6,71,1573211652,1361830016,1.568967e+09,15077424,https://stackoverflow.com/questions/15077424/p...,pros and cons between os.path.exists vs os.pat...,15077441.0,NaN,NaN,NaN,NaN,NaN
154,"[python, mongodb, python-2.7, bottle, mongoeng...","{'reputation': 406, 'user_id': 842108, 'user_t...",True,24980,6,28,1573211544,1352111714,1.352112e+09,13230284,https://stackoverflow.com/questions/13230284/c...,Convert mongodb return object to dictionary,13230510.0,NaN,NaN,NaN,NaN,NaN
165,"[python, pandas, numpy, stata, hdf5]","{'reputation': 18578, 'user_id': 8682794, 'use...",True,9244,6,53,1573210820,1523301691,1.533129e+09,49740190,https://stackoverflow.com/questions/49740190/s...,Saving in a file an array or DataFrame togethe...,49991172.0,NaN,NaN,NaN,NaN,NaN
168,"[python, clipboard, jupyter-notebook]","{'reputation': 43643, 'user_id': 395857, 'user...",True,10960,4,18,1573210707,1495990432,NaN,44229820,https://stackoverflow.com/questions/44229820/h...,How can I copy to the clipboard the output of ...,NaN,NaN,NaN,NaN,NaN,NaN
184,[python],"{'reputation': 38, 'user_id': 3048906, 'user_t...",True,880,3,7,1573209797,1393850327,1.573210e+09,22147050,https://stackoverflow.com/questions/22147050/h...,How to know where an object was instantiated i...,22148022.0,NaN,NaN,NaN,NaN,NaN
192,"[python, python-2.7, exception-handling, stack...","{'reputation': 15356, 'user_id': 505893, 'user...",True,188755,10,368,1573209658,1293728379,1.547625e+09,4564559,https://stackoverflow.com/questions/4564559/ge...,Get exception description and stack trace whic...,4564595.0,NaN,NaN,NaN,NaN,NaN
211,"[python, datetime, weekday]","{'reputation': 11452, 'user_id': 902885, 'user...",True,558803,21,507,1573208794,1332541278,1.573209e+09,9847213,https://stackoverflow.com/questions/9847213/ho...,How do I get the day of week given a date?,9847269.0,NaN,NaN,NaN,NaN,NaN
215,"[python, rsa, pycrypto]","{'reputation': 382, 'user_id': 1968787, 'user_...",True,51845,6,9,1573208441,1390550880,NaN,21327491,https://stackoverflow.com/questions/21327491/u...,"Using pycrypto, how to import a RSA public key...",NaN,NaN,NaN,NaN,NaN,NaN
237,[python],"{'reputation': 2390, 'user_id': 1858864, 'user...",True,2993,2,8,1573207212,1479324502,1.573207e+09,40640674,https://stackoverflow.com/questions/40640674/d...,Differentiate False and 0,40640711.0,NaN,NaN,NaN,NaN,NaN
243,"[python, arrays, machine-learning, indices, da...","{'reputation': 99, 'user_id': 5282599, 'user_t...",True,23331,4,6,1573207044,1477914269,NaN,40341519,https://stackoverflow.com/questions/40341519/h...,How to resolve &quot;IndexError: too many indi...,40341753.0,NaN,NaN,NaN,NaN,NaN
261,"[python, windows, easy-install, cx-oracle]","{'reputation': 21622, 'user_id': 683020, 'user...",True,41755,4,13,1573206415,1340890863,1.495535e+09,11245985,https://stackoverflow.com/questions/11245985/e...,easy_install cx_Oracle (python package) on Win...,11246173.0,NaN,NaN,NaN,NaN,NaN
269,"[python, clipboard, pyperclip]","{'reputation': 628, 'user_id': 1346955, 'user_...",True,141550,11,104,1573206106,1339849967,1.441917e+09,11063458,https://stackoverflow.com/questions/11063458/p...,Python script to copy text to clipboard,NaN,NaN,1.526500e+09,duplicate,NaN,NaN
277,"[python, pandas, printing, column-width]","{'reputation': 2746, 'user_id': 1560238, 'user...",True,503619,15,510,1573205802,1343547891,1.573206e+09,11707586,https://stackoverflow.com/questions/11707586/h...,How do I expand the output display to see more...,11711637.0,1.563355e+09,NaN,NaN,NaN,NaN
281,"[python, python-3.x, tkinter, pyserial]","{'reputation': 46, 'user_id': 12117826, 'user_...",True,106,1,5,1573205714,1572861814,1.573033e+09,58691056,https://stackoverflow.com/questions/58691056/i...,"Issue processing data read from serial port, w...",NaN,NaN,NaN,NaN,100.0,1.573639e+09
297,"[python, lxml, python-2.6, python-import, cent...","{'reputation': 354, 'user_id': 554693, 'user_t...",True,25704,4,32,1573205393,1294621965,1.573205e+09,4642942,https://stackoverflow.com/questions/4642942/se...,Setup.py: install lxml with Python2.6 on CentOS,4643058.0,NaN,NaN,NaN,NaN,NaN
316,"[python, django, datetime, python-2.7]","{'reputation': 508, 'user_id': 3125079, 'user_...",True,6826,3,12,1573204647,1395495150,1.395495e+09,22578272,https://stackoverflow.com/questions/22578272/h...,How to change my django server time,22578283.0,NaN,NaN,NaN,NaN,NaN
333,"[python, dictionary, associative-array, ordere...","{'reputation': 5808, 'user_id': 2112485, 'user...",True,188209,13,340,1573204145,1368161550,1.531252e+09,16475384,https://stackoverflow.com/questions/16475384/r...,Rename a dictionary key,NaN,1.563351e+09,NaN,NaN,NaN,NaN
343,"[python, python-2.7, class, attributes]","{'reputation': 3425, 'user_id': 495557, 'user_...",True,181067,17,78,1573203834,1327885389,1.548931e+09,9058305,https://stackoverflow.com/questions/9058305/ge...,Getting attributes of a class,9058322.0,1.572433e+09,NaN,NaN,NaN,NaN
347,"[python, pandas, dataframe]","{'reputation': 238, 'user_id': 5893958, 'user_...",True,11784,6,21,1573203752,1476089901,1.476096e+09,39954668,https://stackoverflow.com/questions/39954668/h...,How to convert column with list of values into...,39955283.0,NaN,NaN,NaN,NaN,NaN
350,"[python, data-structures, graph]","{'reputation': 168, 'user_id': 1199470, 'user_...",True,2187,6,10,1573203567,1426058819,NaN,28980797,https://stackoverflow.com/questions/28980797/g...,"Given n tuples representing pairs, return a li...",28981597.0,NaN,NaN,NaN,NaN,NaN
365,"[python, jupyter-notebook, jupyter, ipywidgets]","{'reputation': 1831, 'user_id': 314548, 'user_...",True,1282,2,7,1573202407,1486029342,1.573202e+09,41999020,https://stackoverflow.com/questions/41999020/h...,How to make an ipywidgets Image clickable?,NaN,NaN,NaN,NaN,NaN,NaN
379,"[python, class, dictionary, struct]","{'reputation': 8597, 'user_id': 136598, 'user_...",True,47397,12,47,1573201447,1280351916,1.473404e+09,3357581,https://stackoverflow.com/questions/3357581/us...,Using Python class as a data container,3357616.0,NaN,NaN,NaN,NaN,NaN
387,"[python, scikit-learn]","{'reputation': 1366, 'user_id': 4805150, 'user...",True,159368,11,100,1573201228,1433510117,1.550341e+09,30667525,https://stackoverflow.com/questions/30667525/i...,ImportError: No module named sklearn.cross_val...,30667615.0,1.555231e+09,NaN,NaN,NaN,NaN
391,"[python, json, mime-types, flask]","{'reputation': 13226, 'user_id': 586621, 'user...",True,38887,2,41,1573201050,1344916193,1.495542e+09,11945523,https://stackoverflow.com/questions/11945523/f...,Forcing application/json MIME type in a view (...,11945643.0,NaN,NaN,NaN,NaN,NaN
397,"[python, ssl, flask, error-logging, smtplib]","{'reputation': 1433, 'user_id': 3556110, 'user...",True,4792,1,8,1573200706,1461930093,NaN,36937461,https://stackoverflow.com/questions/36937461/h...,How can I send an email using python logging&#...,36937462.0,NaN,NaN,NaN,NaN,NaN
407,"[python, pandas, matplotlib, data-visualizatio...","{'reputation': 4908, 'user_id': 1983512, 'user...",True,320224,9,172,1573200097,1428065842,1.553704e+09,29432629,https://stackoverflow.com/questions/29432629/p...,Plot correlation matrix using pandas,29432741.0,NaN,NaN,NaN,NaN,NaN
411,"[python, virtualenv, psycopg2]","{'reputation': 707, 'user_id': 723511, 'user_t...",True,25453,7,31,1573199929,1341589964,NaN,11365619,https://stackoverflow.com/questions/11365619/p...,psycopg2 installation error - Library not load...,NaN,NaN,NaN,NaN,NaN,NaN
413,"[python, scipy, curve-fitting]","{'reputation': 1026, 'user_id': 1803782, 'user...",True,27792,5,39,1573199853,1423248079,1.423249e+09,28372597,https://stackoverflow.com/questions/28372597/p...,Python curve_fit with multiple independent var...,28373422.0,1.562920e+09,NaN,NaN,NaN,NaN
417,"[python, pandas, csv, dataframe]","{'reputation': 194, 'user_id': 2252633, 'user_...",True,41687,12,24,1573199788,1527426010,1.527503e+09,50552404,https://stackoverflow.com/questions/50552404/o...,OSError: Initializing from file failed on csv ...,52283966.0,NaN,NaN,NaN,NaN,NaN
424,"[python, django, security, django-rest-framework]","{'reputation': 2931, 'user_id': 998687, 'user_...",True,1594,3,10,1573199290,1437350206,1.495543e+09,31507211,https://stackoverflow.com/questions/31507211/h...,How to restrict Django Rest Framework browsabl...,NaN,NaN,NaN,NaN,NaN,NaN
427,"[python, selenium, tor]","{'reputation': 135, 'user_id': 1907403, 'user_...",True,30173,9,25,1573199063,1362865758,NaN,15316304,https://stackoverflow.com/questions/15316304/o...,Open tor browser with selenium,NaN,NaN,NaN,NaN,NaN,NaN
443,"[python, python-3.x]","{'reputation': 46, 'user_id': 8056128, 'user_t...",True,23165,3,5,1573198037,1495577081,1.573198e+09,44145784,https://stackoverflow.com/questions/44145784/c...,Check if key is missing after loading json fro...,NaN,NaN,NaN,NaN,NaN,NaN
446,"[python, class, instance]","{'reputation': 2820, 'user_id': 1472743, 'user...",True,39205,5,12,1573197493,1345218517,1.544208e+09,12008991,https://stackoverflow.com/questions/12008991/p...,python: create instance of class in another cl...,12009396.0,NaN,NaN,NaN,NaN,NaN
449,"[python, jupyter-notebook, tqdm]","{'reputation': 968, 'user_id': 6183298, 'user_...",True,68977,4,94,1573197387,1487017194,NaN,42212810,https://stackoverflow.com/questions/42212810/t...,tqdm in Jupyter Notebook,42218684.0,NaN,NaN,NaN,NaN,NaN
456,[python],"{'reputation': 3210, 'user_id': 458320, 'user_...",True,24688,8,37,1573196795,1289546736,1.480524e+09,4162456,https://stackoverflow.com/questions/4162456/fo...,Forward declaration of classes?,4163042.0,NaN,NaN,NaN,NaN,NaN
466,"[python, python-3.x, pandas, dictionary]","{'reputation': 80, 'user_id': 7797307, 'user_t...",True,9903,2,10,1573195837,1493213425,1.493277e+09,43635694,https://stackoverflow.com/questions/43635694/d...,Difference between dictionary and pandas serie...,43636703.0,NaN,NaN,NaN,NaN,NaN
491,"[python, list-comprehension]","{'reputation': 997, 'user_id': 641235, 'user_t...",True,38396,6,44,1573194412,1335243955,1.392483e+09,10291997,https://stackoverflow.com/questions/10291997/h...,How can I do assignments in a list comprehension?,NaN,NaN,NaN,NaN,NaN,NaN
497,"[python, excel, fonts, conditional-formatting,...","{'reputation': 2548, 'user_id': 4248237, 'user...",True,6775,1,5,1573194076,1441696837,NaN,32451567,https://stackoverflow.com/questions/32451567/o...,openpyxl font conditional formatting,32454012.0,NaN,NaN,NaN,NaN,NaN

#### Question 3: Find the answers with id 6784 and 6473.

In [29]:
# your code here
answers = SITE.fetch('answers', ids = [6784,6473])
answers

{'backoff': 0,
 'has_more': False,
 'page': 1,
 'quota_max': 300,
 'quota_remaining': 300,
 'total': 0,
 'items': [{'owner': {'reputation': 22434,
    'user_id': 758,
    'user_type': 'registered',
    'accept_rate': 77,
    'profile_image': 'https://www.gravatar.com/avatar/0b4adc19284ed0751844d610555dc6b2?s=128&d=identicon&r=PG',
    'display_name': 'Mark Renouf',
    'link': 'https://stackoverflow.com/users/758/mark-renouf'},
   'is_accepted': False,
   'score': 0,
   'last_activity_date': 1218291583,
   'creation_date': 1218291583,
   'answer_id': 6784,
   'question_id': 6778}]}